repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]
        files: '^(src|tests)/'
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [file, python]
        files: '^(src|tests)/'
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [file, python]
        files: '^(src|tests)/'
